service: yolobe-template-azfx

provider:
  name: azure
  location: West US
  runtime: nodejs8

plugins:
  - serverless-azure-functions
  - serverless-webpack
  - serverless-offline

package:
  exclude:
    - node_modules/**
    - .gitignore
    - package.json
    - .git/**

functions:
  echo:
     handler: src/index.echo
     events:
       - http:
          path: /{action}
          method: GET
          request:
            parameters:
              action: true
         x-azure-settings:
           authLevel: anonymous
           methods: #<array> [GET, POST, PUT, DELETE], default - all
                - get
           route: echo/{action:alpha} #<string>, default - <function name>
